### ISSUE TITLE
This template does not render correctly on mobile Safari or Edge (truncated content boxes)

### ISSUE THREAD

**Issue by rsuk-mb** [netlify-templates/content-ops-starter#44]
On the latest iOS version, the content boxes are truncated and large empty spaces are displayed beneath them.

Pretty gutted as I have just spent a day implementing a site with this template :(

Here are a couple of examples:

![IMG_0918](https://github.com/user-attachments/assets/ac05cff3-8e3c-420c-8019-3e5dc6eb121d)
![IMG_0919](https://github.com/user-attachments/assets/361cb0d2-2523-4c14-b120-eb02d7ed3ebb)

**Comment by TomasBankauskas** [comment]
@rsuk-mb thank you for reporting this issue. The fix will be available soon.

**Comment by TomasBankauskas** [comment]
@rsuk-mb [the fix](https://github.com/netlify-templates/content-ops-starter/commit/3d13f4b1f8b7f36f8c3e84d4f66a49637653aa03) was merged to the main.
